name: Get Job Summary
author: Austen Stone
description: Get a GitHub Actions job summary and/or convert it to another format (PDF, markdown, or HTML)
branding:
  icon: "save"
  color: "blue"

inputs:
  name:
    description: The name of the markdown and PDF file
    default: job-summary
    required: false
  create-md-artifact:
    description: Whether to create an artifact with the markdown file
    default: true
    required: false
  artifact-name:
    description: The name of the artifact
    default:
    required: false

outputs:
  job-summary:
    description: The job summary
  md-file:
    description: The path to the markdown file

runs:
  using: "node20"
  main: "dist/index.js"
